### PR TITLE
add database config file

### PR DESCRIPTION
**Pull request by mgjeffries**
The database config file `rare_server.session.sql` can be used to set up a local instance of the sql database.

### CODE REVIEW

**Comment by skratz17** [comment]
Hmmm, I tried running this (via highlight all, cmd+r cmd+r) after connecting to my rare.db file and got `SQLITE_ERROR: near "FOREIGN": syntax error` ... Did this initialization work for you?

We might need to change the way we're setting up the foreign key constraints on tables to match how we had been doing it with SQLite in class examples up to now, where the constraint is actually set in the CREATE TABLE step:


```
CREATE TABLE `Animal` (
	`id`  INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	`name`  TEXT NOT NULL,
	`status` TEXT NOT NULL,
	`breed` TEXT NOT NULL,
	`customer_id` INTEGER NOT NULL,
	`location_id` INTEGER,
	FOREIGN KEY(`customer_id`) REFERENCES `Customer`(`id`),
	FOREIGN KEY(`location_id`) REFERENCES `Location`(`id`)
);
```

**Comment by mgjeffries** [comment]
@skratz17 Good point. I updated the table to set up the foreign keys.

**Review by skratz17 — APPROVED** [review]
Looks good to me 👨‍🎤

**Review by Michaelr-Tyler — APPROVED** [review]
Looks good

**Pull request merged**
